### ISSUE TITLE
Tracking issue:  React Native New Architecture support

### ISSUE THREAD

**Issue by michalchudziak** [callstack/react-native-slider#380]
## Describe the Feature
The tracking issue for adopting React Native's new architecture. JS side should be pretty straightforward as we are not using `UIManager` API, nor `findNodeHandle`. The native side might require some additional work, although thanks to https://reactnative.dev/docs/next/new-architecture-intro the migration should go smooth.

Migration plan 

JS changes:
- [ ] Move the call to `requireNativeComponent` to a separate file
- [ ] Enable codegen support in `package.json`

iOS:
- [ ] Update `Podspec` for the new architecture
- [ ] Implement / extend the generated native interfaces

Android:
- [ ] Configure `gradle` files
- [ ] Implement / extend the generated native interfaces
- [ ] Extend generated abstract classes

Testing:
- [ ] Define and execute test plan for simulator/emulator and some devices

I'm not sure if backward compatibility (old architecture) is an option, but in case it is we should support both configurations.

**Comment by chakrihacker** [comment]
Can I give a shot on this? is anyone started working?

**Comment by BartoszKlonowski** [comment]
@chakrihacker Unfortunately we have already somebody working on this. Sorry for the confusion.
But, thank you **very** much for willing to contribute on that! 💪

**Comment by thymikee** [comment]
Let's make sure to follow the [official migration guideline](https://github.com/react-native-community/RNNewArchitectureLibraries/tree/feat/back-fabric-comp) with manual linking for Android for now. It's a future-proof approach. [RN CLI new arch autolinking](https://github.com/react-native-community/cli/pull/1603) is in the works and there are libraries that provide their own custom linking setup (for righteous reasons of easier installation), which slow down the roll out.
